<a href="https://colab.research.google.com/github/markusfreeman1994-create/Invest_help_Bor.ver1/blob/main/Alg%26Prog_PR9_Pandas_p1_var_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas: базовые операции, работа с датафреймами

# Вариант 20

In [2]:
import pandas as pd

#Задача 1. Базовые операции с `DataFrame`

1.1.1 Файлы `vehicles_sample.csv` и `services_sample.csv` должны содержать информацию о транспортных средствах автосервиса и услугах по обслуживанию этих транспортных средств соответственно.  
1.1.2. Сгенерируйте данные для файлов самостоятельно с использованием НС DeepSeek, исходя из требований к размеру в не менее 100 строк, число столбцов должно соответствовать тематике данных (наличие числовых, текстовых и временных (дата/время) полей обязательно).  
1.1.3. Данные НЕ должны быть "чистыми": требуется наличие пропусков и дубликатов   
1.1.4. Сохраните сгенерированные данные в файлы с указанными именами.  
1.1.5. Добавьте в Colab сгенерированные файлы `vehicles_sample.csv` и `services_sample.csv`  
1.1.6. Загрузите данные из файлов в виде `pd.DataFrame` с названиями `vehicles` и `services`.  
1.1.7. Обратите внимание на корректное считывание данных и на разделители.

In [3]:
vehicles = pd.read_csv('./vehicles_sample.csv', delimiter=',')
services = pd.read_csv('./services_sample.csv', delimiter=',')
services

     service_id  vehicle_id  service_cost  duration_minutes service_date
0             1          70          5729                37   2020-01-15
1             2          15          8330               213   2023-03-26
2             3          54          6334               224   2024-07-29
3             4          60          9924               224   2023-07-08
4             5          97          5330               184   2023-03-26
..          ...         ...           ...               ...          ...
195         196          42          8830               147   2022-12-13
196         197          58          8350               188   2022-01-30
197         198          39          7238               257   2023-06-16
198         199          14          7090               245   2023-06-06
199         200          95          7031               213   2021-08-01

[200 rows x 5 columns]

### 1.2 Для каждой из таблиц выведите основные параметры:
* количество точек данных (строк);
* количество столбцов;
* тип данных каждого столбца.

In [4]:
pd.DataFrame(
    [[vehicles.shape[0], vehicles.shape[1], vehicles.dtypes],
    [services.shape[0], services.shape[1], services.dtypes]],
    columns=['rows', 'columns', 'dtype'],
    index=['vehicles', 'services'])

          rows  columns                                              dtype
vehicles   100        5  vehicle_id      int64
brand          object
ye...
services   200        5  service_id           int64
vehicle_id         ...

### 1.3 Исследуйте, в каких столбцах таблиц содержатся пропуски. Посчитайте долю строк, содержащих пропуски, в отношении к общему количеству строк.

In [5]:
print('vehicles')
print()
print((vehicles.isna()*1)[vehicles.columns].sum()/len(vehicles))
print()
print('services')
print()
print((services.isna()*1)[services.columns].sum()/len(services))

vehicles

vehicle_id     0.0
brand          0.0
year           0.0
mileage        0.0
description    0.0
dtype: float64

services

service_id          0.0
vehicle_id          0.0
service_cost        0.0
duration_minutes    0.0
service_date        0.0
dtype: float64

### 1.4 Рассчитайте среднее значение для каждого из числовых столбцов (где это имеет смысл).

In [6]:
print('средний пробег автомобиля: '+str(vehicles.mileage.mean()))
print('средняя стоимость услуги: '+str(services.service_cost.mean()))

средний пробег автомобиля: 158197.67
средняя стоимость услуги: 5824.405

In [7]:
print('средний год выпуска автомобиля: ' + str(vehicles.year.mean()))
print('средняя длительность обслуживания: ' + str(services.duration_minutes.mean()))

средний год выпуска автомобиля: 2009.99
средняя длительность обслуживания: 150.31

### 1.5 Вывод статистической информации.

In [ ]:
print('vehicles')
print(vehicles.describe(include='all'))
print()
print('services')
print(services.describe(include='all'))

### 1.6 Измените индекс в таблице `services`, пронумеровав строки, начиная с нуля

In [8]:
services.reset_index(inplace=True, drop=True)
services

     service_id  vehicle_id  service_cost  duration_minutes service_date
0             1          70          5729                37   2020-01-15
1             2          15          8330               213   2023-03-26
2             3          54          6334               224   2024-07-29
3             4          60          9924               224   2023-07-08
4             5          97          5330               184   2023-03-26
..          ...         ...           ...               ...          ...
195         196          42          8830               147   2022-12-13
196         197          58          8350               188   2022-01-30
197         198          39          7238               257   2023-06-16
198         199          14          7090               245   2023-06-06
199         200          95          7031               213   2021-08-01

[200 rows x 5 columns]

### 1.7 Выведите информацию о транспортных средствах, пробег которых не больше 100000 км и год выпуска которых не меньше 2018.

In [9]:
vehicles[(vehicles.mileage <= 100000) & (vehicles.year >= 2018)]

    vehicle_id   brand  year  mileage           description
29          30    Audi  2022    99045   Экономичный вариант
30          31    Audi  2023    44698  Комфортный и быстрый
35          36    Ford  2021    25708   Экономичный вариант
45          46  Toyota  2022    81295   Надежный автомобиль
53          54  Toyota  2018    40306  Комфортный и быстрый
67          68     Kia  2018    76690    Отличное состояние
68          69     BMW  2021    14499    Отличное состояние
72          73     BMW  2020    42711   Экономичный вариант
92          93     BMW  2018    68871   Экономичный вариант

### 1.8 Выведите информацию об услугах, стоимость которых не больше 5000 рублей и длительность не больше 120 минут.

In [10]:
services[(services.service_cost <= 5000) & (services.duration_minutes <= 120)]

     service_id  vehicle_id  service_cost  duration_minutes service_date
10           11           6          1953                34   2023-12-05
13           14          47          2542                51   2022-01-24
18           19          16          3681                75   2024-08-10
19           20          13          2540                63   2020-01-11
22           23          17          2365               102   2021-07-03
28           29          90          4141                85   2020-10-28
30           31          62          4486                77   2021-01-30
31           32          23          2810                90   2020-08-05
44           45          64          4072               107   2020-12-21
47           48          22          2214                43   2023-03-02
50           51          76          1823                32   2023-02-03
55           56          57          4627                44   2022-10-10
62           63          62          2256               115   2022-02-17
66           67          90          4584                42   2024-06-24
68           69          48          4330                54   2023-10-01
69           70          85          3703                97   2024-07-03
77           78         100          1667                63   2022-07-24
81           82          10          3745               112   2023-08-25
103         104          51          1009                35   2022-08-12
110         111          74          3193                91   2023-04-18
119         120          35          2633                49   2021-10-27
122         123          90          1384                76   2022-12-08
123         124           8          1404                30   2022-08-24
138         139          10          1716               113   2024-10-25
147         148          96          1770               105   2021-10-31
149         150          23          2077                30   2023-08-21
156         157          23          3814                34   2020-01-18
157         158          89          4374               107   2022-02-07
158         159          99          2252                91   2021-08-12
168         169          49          2331                52   2024-08-28
176         177          28          3180                68   2022-03-10
179         180          52          1137                96   2020-06-10
181         182          16          4472                71   2020-03-27
191         192          16          4818               115   2022-01-28
192         193          57          2906                39   2021-03-18

#Задача 2. Работа с датами в `pandas`

### 2.1 В столбце service_date по смыслу находится дата оказания услуги. Однако сейчас данное значение воспринимается просто как строка. Это обстоятельство не позволит нам анализировать даты. Преобразуйте столбец `service_date` из таблицы `services` в формат времени с помощью функции pd.to_datetime.

In [11]:
services.service_date = pd.to_datetime(services.service_date)
services.service_date

0     2020-01-15
1     2023-03-26
2     2024-07-29
3     2023-07-08
4     2023-03-26
         ...
195   2022-12-13
196   2022-01-30
197   2023-06-16
198   2023-06-06
199   2021-08-01
Name: service_date, Length: 200, dtype: datetime64[ns]

### 2.2 Выведите информацию об услугах, оказанных в датасет не позже 2022 года.

In [12]:
services[services.service_date.dt.year >= 2022]

     service_id  vehicle_id  service_cost  duration_minutes service_date
1             2          15          8330               213   2023-03-26
2             3          54          6334               224   2024-07-29
3             4          60          9924               224   2023-07-08
4             5          97          5330               184   2023-03-26
7             8          60          5846                90   2022-04-23
..          ...         ...           ...               ...          ...
193         194          39          7254                34   2024-11-25
195         196          42          8830               147   2022-12-13
196         197          58          8350               188   2022-01-30
197         198          39          7238               257   2023-06-16
198         199          14          7090               245   2023-06-06

[126 rows x 5 columns]

### 2.3 Выведите информацию об услугах, оказанных в датасет в августе (services.service_date.dt.month == 8).

In [13]:
services[services.service_date.dt.month == 8]

     service_id  vehicle_id  service_cost  duration_minutes service_date
14           15          99          6293                30   2023-08-08
18           19          16          3681                75   2024-08-10
31           32          23          2810                90   2020-08-05
34           35           1          6301                37   2022-08-15
52           53          16          6029               267   2021-08-26
59           60          69          5175               231   2023-08-12
60           61          47          6348                68   2023-08-13
80           81          95          4719               265   2022-08-26
81           82          10          3745               112   2023-08-25
87           88           4          7042               258   2024-08-16
91           92           2          7132               141   2020-08-31
103         104          51          1009                35   2022-08-12
123         124           8          1404                30   2022-08-24
141         142          64          5544                67   2020-08-02
143         144          49          4419               124   2022-08-09
149         150          23          2077                30   2023-08-21
158         159          99          2252                91   2021-08-12
168         169          49          2331                52   2024-08-28
169         170         100          5261                92   2022-08-04
199         200          95          7031               213   2021-08-01

##Задача 3. Работа со строковыми данными в `pandas`

### 3.1 Измените название каждой марки автомобиля в таблице `vehicles` таким образом, чтобы каждое слово в названии начиналось с прописной буквы.

In [14]:
vehicles.brand = vehicles.brand.str.title()
vehicles

    vehicle_id    brand  year  mileage           description
0            1      Kia  2014   128451  Комфортный и быстрый
1            2  Hyundai  2012    49353  Комфортный и быстрый
2            3     Audi  2000   203075  Комфортный и быстрый
3            4  Hyundai  2006   224283  Комфортный и быстрый
4            5  Hyundai  2008    75318  Комфортный и быстрый
..         ...      ...   ...      ...                   ...
95          96      Kia  2023   266687    Отличное состояние
96          97      Kia  2014   211163  Комфортный и быстрый
97          98  Hyundai  2021   117450   Надежный автомобиль
98          99   Toyota  2023   181890             Как новый
99         100  Hyundai  2008   291974    Отличное состояние

[100 rows x 5 columns]

### 3.2 Добавьте в таблицу `vehicles` столбец `name_word_count`, в котором хранится количество слов из названия марки (считайте, что слова в названии разделяются только пробелами). Обратите внимание, что между словами может располагаться несколько пробелов подряд.

In [15]:
vehicles = vehicles.assign(name_word_count=vehicles.brand.str.split().str.len())
vehicles

    vehicle_id    brand  year  mileage           description  name_word_count
0            1      Kia  2014   128451  Комфортный и быстрый                1
1            2  Hyundai  2012    49353  Комфортный и быстрый                1
2            3     Audi  2000   203075  Комфортный и быстрый                1
3            4  Hyundai  2006   224283  Комфортный и быстрый                1
4            5  Hyundai  2008    75318  Комфортный и быстрый                1
..         ...      ...   ...      ...                   ...              ...
95          96      Kia  2023   266687    Отличное состояние                1
96          97      Kia  2014   211163  Комфортный и быстрый                1
97          98  Hyundai  2021   117450   Надежный автомобиль                1
98          99   Toyota  2023   181890             Как новый                1
99         100  Hyundai  2008   291974    Отличное состояние                1

[100 rows x 6 columns]

### 3.3 Добавьте в таблицу vehicles столбец description_word_count, в котором хранится количество слов в описании автомобиля (считайте, что слова в описании разделяются только пробелами).

In [16]:
vehicles = vehicles.assign(description_word_count=vehicles.description.str.split().str.len())
vehicles

,vehicle_id,brand,year,mileage,description,name_word_count,description_word_count
0,1,Kia,2014,128451,Комфортный и быстрый,1,3
1,2,Hyundai,2012,49353,Комфортный и быстрый,1,3
2,3,Audi,2000,203075,Комфортный и быстрый,1,3
3,4,Hyundai,2006,224283,Комфортный и быстрый,1,3
4,5,Hyundai,2008,75318,Комфортный и быстрый,1,3
...,...,...,...,...,...,...,...
95,96,Kia,2023,266687,Отличное состояние,1,2
96,97,Kia,2014,211163,Комфортный и быстрый,1,3
97,98,Hyundai,2021,117450,Надежный автомобиль,1,2
98,99,Toyota,2023,181890,Как новый,1,2
99,100,Hyundai,2008,291974,Отличное состояние,1,2

### 3.4 Отсортируйте таблицу в порядке убывания величины столбца `name_word_count` и сохраните ее в csv файл.

In [18]:
vehicles.sort_values('name_word_count', ascending=False).to_csv('./sorted_vehicles.csv')

# Задача 4. Работа с DataFrame

<b>Генерация данных: </b>
1. Файл `maintenance.csv` должен содержать информацию о техническом обслуживании.
2. Сгенерируйте данные для датасета `maintenance` самостоятельно с использованием НС DeepSeek или возможностей Pandas. Этот датасет должен содержать следующую информацию:
* id - идентификатор обслуживания
* brand - марка автомобиля
* service_type - тип услуги
* mechanic - механик
* date - день обслуживания
* year - год обслуживания
* month - месяц обслуживания
* details - детали обслуживания
3. В датасете должно быть не менее 10_000 строк, наличие числовых, текстовых и временных (дата/время) полей обязательно.
4. Данные НЕ должны быть "чистыми": требуется наличие пропусков и дубликатов
5. Сохраните сгенерированные данные в файл `maintenance.csv`.

In [20]:
import pandas as pd

Загрузите таблицу с данными из `maintenance.csv`

In [21]:
maintenance = pd.read_csv('./maintenance.csv')

Посмотрите на первые 5 строк датафрейма (метод `head`):

**Пример вывода**

```
	id	brand	service_type	mechanic	date	year	month	details
0	20001	Toyota Camry	Oil Change	Ivan Petrov	2022-01-15	2022	1	Regular maintenance...
1	20002	Honda Civic	Brake Repair	Anna Smirnova	2022-02-20	2022	2	Front brakes...
2	20003	Ford Focus	Tire Rotation	Ivan Petrov	2022-03-05	2022	3	All seasons...
3	20004	BMW X5	Engine Check	Sergey Volkov	2022-04-10	2022	4	Diagnostic...
4	20005	Mercedes C-Class	Transmission	Anna Smirnova	2022-05-12	2022	5	Fluid change...
```

Определите количество строк и столбцов в датафрейме (атрибут `shape`)

In [22]:
maintenance.shape

(10300, 8)

`(50000, 8)`

Посмотрите, в каких столбцах есть пропуски (используйте методы ```isnull``` и ```sum```)

In [23]:
maintenance.isnull().sum()

id                0
brand           206
service_type    205
mechanic        203
date              0
details         205
year              0
month             0
dtype: int64

```
id                0
brand             0
service_type      0
mechanic       6600
date              0
year              0
month             0
details           0
dtype: int64
```

Видим, что в колонке ```mechanic``` есть пропуски.

Посчитайте, какая доля пропусков содержится в этой колонке (используйте методы ```isnull``` и ```mean```)

In [25]:
maintenance['mechanic'].isnull().mean()

np.float64(0.01970873786407767)

`0.132`

Видим, что в колонке ```mechanic``` 13.2% пропусков. Давайте удалим те строки, в которых пропущено значение в колонке ```mechanic```

Для этого используйте функцию ```dropna```, которой в качестве аргумента можно передать параметр ```axis```, чтобы удалить строки или столбцы с пропусками.

Не забудьте, что чтобы сохранить результат удаления строк, нужно либо перезаписать датафрейм (```df = df.dropna()```), либо выставить в методе ```dropna``` параметр ```inplace=True```, который говорит о том, что операция будет производиться с самим датафреймом, а не с его копией

In [29]:
maintenance.dropna(subset=['mechanic'], inplace=True)

Проверим размер датафрейма после удаления пропусков и убедимся, что в датафрейме теперь нет пропусков в данных

In [ ]:
maintenance.shape

`(43400, 8)`

In [30]:
maintenance.isnull().sum()

id                0
brand           201
service_type    198
mechanic          0
date              0
details         197
year              0
month             0
dtype: int64

```
id             0
brand          0
service_type   0
mechanic       0
date           0
year           0
month          0
details        0
dtype: int64
```

Проделайте следующие базовые операции с датафреймами:

# Задача 5

Определите количество различных типов услуг (столбец `service_type`) в таблице и их имена (используйте для этого методы датафрейма ```unique``` или ```nunique```):

In [31]:
maintenance['service_type'].nunique()

7

`11`

In [32]:
maintenance['service_type'].nunique()

7

```
array(['Oil Change', 'Brake Repair', 'Tire Rotation', 'Engine Check', 'Transmission', 'Battery Replace', 'Air Filter', 'Coolant Flush', 'Wheel Alignment', 'Spark Plugs', 'AC Service'], dtype=object)
```

# Задача 6

Найдите количество проведённых обслуживаний в отрезке с ```2022-10-01``` по ```2023-04-30``` (включая эти дни)

Для этого используйте фильтрацию по условию. С датами можно обращаться просто как со строками.

При желании это все можно написать одной строкой.

**Подсказка:** найдите строки c датой обслуживания ```>=``` стартовой даты и получите булеву маску. Аналогично получите булеву маску для второй даты. Затем с помощью операции ```&``` над двумя булевыми масками получите новый булев массив, в котором ```True``` будет стоять только у тех строк, у которых дата обслуживания попадает в желаемый отрезок. А затем используйте эту булеву маску как индексы датафрейма.

In [33]:
maintenance[(maintenance['date'] >= '2022-10-01') & (maintenance['date'] <= '2023-04-30')].shape[0]

1421

`17000`

# Задача 7

Какой тип услуги был наиболее популярен в 2022 году?

In [34]:
maintenance[maintenance['year'] == 2022]['service_type'].value_counts().index[0]

'Замена масла'

`'Oil Change'`

# Задача 8

Посчитайте количество обслуживаний, проведённых механиком *Ivan Petrov* в каждом году.

Для этого сначала отберите строки, в которых механиком является *Ivan Petrov*, а затем создайте счетчик из столбца ```year``` (для этого просто позовите метод ```value_counts()``` от столбца ```year```)

In [35]:
maintenance[maintenance['mechanic'] == 'Ivan Petrov']['year'].value_counts()

year
2023    431
2022    423
2021    418
2024    392
Name: count, dtype: int64

```
2022    185
2021    160
Name: year, dtype: int64
```

# Задача 9

Выпишите названия 3х первых марок автомобилей, которые обслуживал механик *Anna Smirnova* в 2022 году.

**Подсказка 1:** после отбора обслуживаний по механику и году, не забудьте отсортировать датафрейм по столбцу даты обслуживания.

**Подсказка 2:** срезы по строкам датафреймов работают так же, как срезы по спискам.

In [36]:
maintenance[
    (maintenance['mechanic'] == 'Anna Smirnova') &
    (maintenance['year'] == 2022)
].sort_values('date')['brand'].head(3).values

array(['Toyota', 'Audi', 'Skoda'], dtype=object)

```
array(['Toyota Camry', 'Honda Civic', 'BMW X5'],
      dtype=object)
```

# Задача 10

Какой механик на пятидесятом месте по количеству проведённых обслуживаний? Сколько обслуживаний он провёл?

**Подсказка:** для подсчета встречаемости значений используйте метод ```value_counts```. Для доступа к индексам полученного после ```value_counts``` ```pd.Series``` используйте атрибут ```index```

In [44]:
counts = maintenance['mechanic'].value_counts()

counts.index[min(49, len(counts) - 1)]

'Ivan Petrov'

`'Olga Kuznetsova'`

In [45]:
counts.iloc[min(49, len(counts) - 1)]

np.int64(1664)

`65`